name: big-bear-authentik
services:
  big-bear-authentik:
    cpu_shares: 90
    command:
      - server
    container_name: big-bear-authentik
    depends_on:
      big-bear-authentik-db:
        condition: service_started
        required: true
      big-bear-authentik-redis:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          memory: 3754M
    environment:
      - AUTHENTIK_POSTGRESQL__HOST=big-bear-authentik-db
      - AUTHENTIK_POSTGRESQL__NAME=authentik
      - AUTHENTIK_POSTGRESQL__PASSWORD=authentik-password
      - AUTHENTIK_POSTGRESQL__USER=authentik
      - AUTHENTIK_REDIS__HOST=big-bear-authentik-redis
      - AUTHENTIK_SECRET_KEY=changeme
    hostname: big-bear-authentik
    image: ghcr.io/goauthentik/server:2024.4.2
    labels:
      icon: https://github.com/walkxcode/dashboard-icons/blob/main/png/authentik.png?raw=true
    ports:
      - mode: ingress
        target: 9443
        published: "9449"
        protocol: tcp
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/big-bear-authentik/data/authentik-media
        target: /media
        bind:
          create_host_path: true
      - type: bind
        source: /DATA/AppData/big-bear-authentik/data/authentik-custom-templates
        target: /templates
        bind:
          create_host_path: true
    x-casaos:
      ports:
        - container: "7575"
          description:
            en_us: "Container Port: 7575"
      volumes:
        - container: /app/data/configs
          description:
            en_us: "Container Path: /app/data/configs"
        - container: /app/public/icons
          description:
            en_us: "Container Path: /app/public/icons"
        - container: /data
          description:
            en_us: "Container Path: /data"
    devices: []
    cap_add: []
    networks:
      - big_bear_authentik_network
    privileged: false
  big-bear-authentik-db:
    cpu_shares: 90
    command: []
    container_name: big-bear-authentik-db
    deploy:
      resources:
        limits:
          memory: 3754M
    environment:
      - POSTGRES_DB=authentik
      - POSTGRES_PASSWORD=authentik-password
      - POSTGRES_USER=authentik
    hostname: big-bear-authentik-db
    healthcheck:
      test:
        - CMD-SHELL
        - "pg_isready -d  -U "
      timeout: 5s
      interval: 30s
      retries: 5
      start_period: 20s
    image: postgres:12-alpine
    labels:
      icon: https://github.com/walkxcode/dashboard-icons/blob/main/png/authentik.png?raw=true
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/big-bear-authentik/data/postgres
        target: /var/lib/postgresql/data
        bind:
          create_host_path: true
    x-casaos:
      envs:
        - container: POSTGRES_PASSWORD
          description:
            en_us: Database password
        - container: POSTGRES_USER
          description:
            en_us: Database user
        - container: POSTGRES_DB
          description:
            en_us: Database type
      volumes:
        - container: /var/lib/postgresql/data
          description:
            en_us: "Container Path: /var/lib/postgresql/data"
    ports: []
    devices: []
    cap_add: []
    networks:
      - big_bear_authentik_network
    privileged: false
  big-bear-authentik-redis:
    cpu_shares: 90
    command:
      - --save
      - "60"
      - "1"
      - --loglevel
      - warning
    container_name: big-bear-authentik-redis
    deploy:
      resources:
        limits:
          memory: 3754M
    hostname: big-bear-authentik-redis
    healthcheck:
      test:
        - CMD-SHELL
        - redis-cli ping | grep PONG
      timeout: 3s
      interval: 30s
      retries: 5
      start_period: 20s
    image: redis:alpine
    labels:
      icon: https://github.com/walkxcode/dashboard-icons/blob/main/png/authentik.png?raw=true
    restart: unless-stopped
    volumes:
      - type: bind
        source: /DATA/AppData/big-bear-authentik/data/redis
        target: /data
        bind:
          create_host_path: true
    x-casaos:
      volumes:
        - container: /data
          description:
            en_us: "Container Path: /data"
    ports: []
    devices: []
    cap_add: []
    environment: []
    networks:
      - big_bear_authentik_network
    privileged: false
  big-bear-authentik-worker:
    cpu_shares: 90
    command:
      - worker
    container_name: big-bear-authentik-worker
    depends_on:
      big-bear-authentik-db:
        condition: service_started
        required: true
      big-bear-authentik-redis:
        condition: service_started
        required: true
    deploy:
      resources:
        limits:
          memory: 3754M
    environment:
      - AUTHENTIK_POSTGRESQL__HOST=big-bear-authentik-db
      - AUTHENTIK_POSTGRESQL__NAME=authentik
      - AUTHENTIK_POSTGRESQL__PASSWORD=authentik-password
      - AUTHENTIK_POSTGRESQL__USER=authentik
      - AUTHENTIK_REDIS__HOST=big-bear-authentik-redis
      - AUTHENTIK_SECRET_KEY=changeme
    hostname: big-bear-authentik-worker
    image: ghcr.io/goauthentik/server:2024.4.2
    labels:
      icon: https://github.com/walkxcode/dashboard-icons/blob/main/png/authentik.png?raw=true
    restart: unless-stopped
    user: root
    volumes:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
        bind:
          create_host_path: true
      - type: bind
        source: /DATA/AppData/big-bear-authentik/data/authentik-media
        target: /media
        bind:
          create_host_path: true
      - type: bind
        source: /DATA/AppData/big-bear-authentik/data/authentik-certs
        target: /certs
        bind:
          create_host_path: true
      - type: bind
        source: /DATA/AppData/big-bear-authentik/data/authentik-custom-templates
        target: /templates
        bind:
          create_host_path: true
    x-casaos:
      volumes:
        - container: /media
          description:
            en_us: "Container Path: /media"
        - container: /certs
          description:
            en_us: "Container Path: /certs"
        - container: /templates
          description:
            en_us: "Container Path: /templates"
    ports: []
    devices: []
    cap_add: []
    networks:
      - big_bear_authentik_network
    privileged: false
networks:
  big_bear_authentik_network:
    name: big-bear-authentik_big_bear_authentik_network
    driver: bridge
x-casaos:
  architectures:
    - amd64
    - arm64
  author: BigBearTechWorld
  category: BigBearCasaOS
  description:
    en_us: Authentik is a self-hosted identity and access management platform that
      provides a secure and scalable solution for managing user accounts,
      authentication, and authorization. It offers a range of features,
      including user management, role-based access control, and multi-factor
      authentication. Authentik is designed to be easy to use and integrate with
      your existing systems, making it a great choice for organizations looking
      to improve their security and compliance.
  developer: authentik
  hostname: dmnetcloud.tail91bff.ts.net
  icon: https://github.com/walkxcode/dashboard-icons/blob/main/png/authentik.png?raw=true
  index: /
  is_uncontrolled: false
  main: big-bear-authentik
  port_map: "9449"
  scheme: https
  store_app_id: big-bear-authentik
  tagline:
    en_us: Authentik
  thumbnail: ""
  tips:
    before_install:
      en_us: >
        Before you install read this:
        https://community.bigbeartechworld.com/t/added-authentik-to-bigbearcasaos/1196#instructions-3
  title:
    custom: ""
    en_us: Authentik
