---
- name: Retrieve and display disk size on Windows
  hosts: all
  gather_facts: no
  tasks:
    - name: Get disk size using PowerShell
      win_shell: |
        $disks = Get-PhysicalDisk | Select-Object DeviceId, MediaType, Size | ConvertTo-Json -Depth 2
        Write-Output $disks
      register: disk_info

    - name: Display formatted disk information
      debug:
        msg: "{{ disk_info.stdout | from_json }}"
