- name: Retrieve and display disk size on Windows
  hosts: all
  gather_facts: no
  tasks:
    - name: Get disk size using PowerShell
      win_shell: |
        $disks = Get-PhysicalDisk | Select-Object DeviceId, MediaType, @{
          Name = 'SizeGB'
          Expression = { [math]::Round($_.Size / 1GB, 2) }
        } | ConvertTo-Json -Depth 2
        Write-Output $disks
      register: disk_info

    - name: Display formatted disk information
      debug:
        msg: "Disk {{ item.DeviceId }} ({{ item.MediaType }}): {{ item.SizeGB }} GB"
      loop: "{{ disk_info.stdout | from_json }}"
