---
- name: Retrieve and display disk size on Windows
  hosts: all
  gather_facts: no
  tasks:
    - name: Gather disk facts
      win_disk_facts:

    - name: Display disk information
      debug:
        msg: "{{ ansible_facts['disks'] }}"
