- name: Gather Disk Status
  hosts: win
  tasks:
    - name: Gather system facts
      setup:

    - name: Filter and print disk information (Linux)
      debug:
        var: item
      with_items: "{{ ansible_mounts }}"
      loop_control:
        label: "{{ item.mount }}"
      when: ansible_os_family in ["Debian", "RedHat"] and item.mount not in ['/mnt', '/dev', '/run', '/sys', '/proc', '/boot', '/tmp', '/var']
      register: linux_disks
      tags: linux_disks

    - name: Get disk status (Windows)
      win_command: Get-PSDrive -PSProvider FileSystem | Select-Object Used,Free,Name
      register: win_disk_status
      when: ansible_os_family == "Windows"

    - name: Print disk information (Windows)
      debug:
        var: win_disk_status.stdout_lines
      when: ansible_os_family == "Windows"
