- name: Gather Host Information
  hosts: all

  gather_facts: yes

  tasks:
    - name: Display hostname
      debug:
        msg: "Hostname: {{ ansible_hostname }}"

    - name: Display IP addresses
      debug:
        msg: "IP Addresses: {{ ansible_all_ipv4_addresses }}"

    - name: Display distribution
      debug:
        msg: "Distribution: {{ ansible_distribution }}"
