---
- name: Playbook Name
  hosts: win
  gather_facts: true
  tasks:
    - name :  Find all services that start with 'win'
      ansible.windows.win_service :
          name : VMMS
          start_mode: auto
          state : started
      register : service_info
    - name : debug
      debug : 
        msg : "Service Name: {{ service_info.display_name }}, State: {{ service_info.state }}, Start Mode: {{ service_info.start_mode }}"

    - name: Get hostname
      win_shell: |
        hostname
      register: machine_info

    - name: Debug hostname information
      debug:
        var: machine_info