---
- name: Setup Docker, Docker Compose, Kubernetes, and LXC on Debian Bookworm
  hosts: all
  become: true

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install required base packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - software-properties-common
          - lxc
          - lxc-templates
        state: present

    # ------------------------ Docker ------------------------

    - name: Add Docker GPG key (modern method)
      shell: |
        install -m 0755 -d /etc/apt/keyrings
        curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
        chmod a+r /etc/apt/keyrings/docker.gpg
      args:
        creates: /etc/apt/keyrings/docker.gpg

    - name: Add Docker apt repository
      apt_repository:
        repo: "deb https://apt.kubernetes.io/ kubernetes main"
        filename: docker
        state: present

    - name: Install Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest
        update_cache: yes

    - name: Enable and start Docker
      systemd:
        name: docker
        enabled: yes
        state: started

    # ---------------- Docker Compose Plugin ----------------

    - name: Get latest Docker Compose version
      shell: |
        curl -s https://api.github.com/repos/docker/compose/releases/latest | grep tag_name | cut -d '"' -f 4
      register: compose_latest_version
      changed_when: false

    - name: Create directory for Docker CLI plugins
      file:
        path: /usr/local/lib/docker/cli-plugins
        state: directory
        mode: '0755'
        recurse: yes

    - name: Download latest Docker Compose plugin
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ compose_latest_version.stdout }}/docker-compose-linux-x86_64"
        dest: /usr/local/lib/docker/cli-plugins/docker-compose
        mode: '0755'

    - name: Create symlink for docker-compose
      file:
        src: /usr/local/lib/docker/cli-plugins/docker-compose
        dest: /usr/bin/docker-compose
        state: link
        force: true

    # -------------------- Kubernetes ------------------------

    - name: Add Kubernetes GPG key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present

    - name: Add Kubernetes apt repository
      apt_repository:
        repo: "deb https://apt.kubernetes.io/ kubernetes-xenial main"
        filename: kubernetes
        state: present

    - name: Install Kubernetes components
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: latest
        update_cache: yes

    - name: Hold Kubernetes packages to prevent auto upgrade
      apt:
        name:
          - kubelet
          - kubeadm
          - kubectl
        state: hold

    # ------------------------- LXC --------------------------

    - name: Enable and start LXC service
      systemd:
        name: lxc
        enabled: yes
        state: started
