---
- name: Windows Update Playbook
  hosts: all
  
  tasks:
    
    - debug:
        msg: my Machine name is  {{ansible_hostname}} 
              and OS Type is {{ansible_os_product_type}} 
               OS Build version is {{ansible_distribution_version}}
               IPV4 address is {{ansible_facts.default.ipv4.address}}
               
        
     

    - name: Apply update programs
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - Updates
        server_selection: managed_server
        state: "{{Update_State}}"
      register: result

    - debug: var=result
