---
- name: Simple Disk Usage Report with SFTP Upload
  hosts: all
  gather_facts: yes
  vars:
    sftp_host: "dmnetcloud"
    sftp_port: "2022"
    sftp_user: "dharmesh"
    sftp_password: "Thankgod@123"
    remote_path: "/imp/sfs_ansible"
    report_file: "/tmp/disk_usage_report_{{ ansible_hostname }}.txt"
    
  tasks:
    - name: Collect disk usage data (excluding mount points)
      shell: df -h | grep -v "^Filesystem" | awk '{print $5 " used on " $1 " (" $2 " total, " $4 " free)"}'
      register: df_output
      
    - name: Create simple disk usage report
      copy:
        content: |
          ===================================================
          DISK USAGE REPORT FOR {{ ansible_hostname }}
          Generated on {{ ansible_date_time.date }}
          ===================================================
          
          {{ df_output.stdout }}
          
          ===================================================
        dest: "{{ report_file }}"
        
    - name: Install sshpass if not present
      package:
        name: sshpass
        state: present
      become: yes
      
    - name: Upload report via SFTP using simple command
      shell: |
        echo "{{ sftp_password }}" | sshpass -p "{{ sftp_password }}" sftp -o StrictHostKeyChecking=no -P {{ sftp_port }} {{ sftp_user }}@{{ sftp_host }}:{{ remote_path }} << EOF
        put {{ report_file }}
        bye
        EOF
      args:
        executable: /bin/bash
        
    - name: Report upload status
      debug:
        msg: "Disk usage report uploaded to SFTP server"
