---
- name: Show Current Disk Space
  hosts: all
  become: yes

  tasks:
    - name: Get disk space usage
      command: df -h
      register: disk_space

    - name: Display disk space usage
      ansible.builtin.debug:
        msg: "{{ disk_space.stdout }}"
