---
- name: Show Disk Usage with duf
  hosts: all
  become: yes

  tasks:
    - name: Ensure duf is installed
      apt:
        name: duf
        state: present
      # Adjust this task if your system uses a different package manager or if you need to add a repository.

    - name: Get disk usage information with duf
      command: duf
      register: duf_output

    - name: Display disk usage information
      ansible.builtin.debug:
        msg: "{{ duf_output.stdout }}"
