----

-- name: Upgrade and Reboot RHEL & Debian family Linux distros

-  hosts: all

- 

-  tasks:

-    # Upgrade RHEL family OS packages

-    - name: Upgrade RHEL Family OS packages

-      yum:

-        name: '*'

-        state: latest

-        skip_broken: true

-      when: ansible_os_family == "RedHat"

-    # Debian Family upgrade

-    - name: Update repositories cache

-      apt:

-        update_cache: yes

-      when: ansible_os_family == "Debian"

-    - name: Update all packages to their latest version

-      apt:

-        name: "*"

-        state: latest

-      when: ansible_os_family == "Debian"

-    - name: Upgrade the OS (apt-get dist-upgrade)

-      apt:

-        upgrade: dist

-      when: ansible_os_family == "Debian"

