---
- name: Disk Usage Report without Overlay, tmpfs, and Network Mounts
  hosts: all
  gather_facts: yes
  vars:
    sftp_host: "dmnetcloud"
    sftp_port: "2022"
    sftp_user: "dharmesh"
    sftp_password: "Thankgod@123"
    remote_path: "/imp/sfs_ansible"
    timestamp: "{{ ansible_date_time.year }}{{ ansible_date_time.month }}{{ ansible_date_time.day }}_{{ ansible_date_time.hour }}{{ ansible_date_time.minute }}"
    report_file: "/tmp/{{ ansible_hostname }}_{{ timestamp }}.txt"

  tasks:
    - name: Collect disk usage excluding overlay, tmpfs, and network mounts
      shell: df -h | awk 'NR>1 && $1 !~ /overlay/ && $1 !~ /^\/\// && $1 !~ /tmpfs/ {print $5 " used on " $1 " (" $2 " total, " $4 " free)"}'
      register: df_output

    - name: Create disk usage report file
      copy:
        content: |
          ===================================================
          DISK USAGE REPORT FOR {{ ansible_hostname }}
          Generated on {{ ansible_date_time.date }} at {{ ansible_date_time.time }}
          ===================================================
          
          {{ df_output.stdout }}
          
          ===================================================
        dest: "{{ report_file }}"

    - name: Ensure sshpass is installed
      package:
        name: sshpass
        state: present
      become: yes

    - name: Upload report via SFTP
      shell: |
        sshpass -p "{{ sftp_password }}" sftp -o StrictHostKeyChecking=no -P {{ sftp_port }} {{ sftp_user }}@{{ sftp_host }} << EOF
        put {{ report_file }} {{ remote_path }}
        bye
        EOF
      args:
        executable: /bin/bash

    - name: Confirm report upload
      debug:
        msg: "Disk usage report successfully uploaded to SFTP: {{ remote_path }}/{{ report_file | basename }}"
