---

- name: Upgrade and Reboot RHEL & Debian family Linux distros

  hosts: all
  tasks:
   - name : Update Debian OS 
     apt : 
      update_cache: yes
      state: latest
     when: ansible_os_family == "Debian"
     register: update
     ignore_errors: yes
   - name: debug
     debug: 
       var: update  