- name: Get Debian OS Disk Usage and Save Locally
  hosts: all
  gather_facts: no
  vars:
    local_output_file: "/tmp/disk_usage.txt"
  tasks:
    - name: Get disk usage using df
      command: df -h
      register: disk_usage_output

    - name: Save disk usage information to a local file
      copy:
        content: "{{ disk_usage_output.stdout }}"
        dest: "{{ local_output_file }}"

    - name: Check if local disk usage file exists
      stat:
        path: "{{ local_output_file }}"
      register: disk_usage_file_stat

    - name: Display file existence
      debug:
        msg: "Local disk usage file exists: {{ disk_usage_file_stat.stat.exists }}"
