----
-- name: Show all disk free space in tree format
-  hosts: all
-  gather_facts: no
-  tasks:
-    - name: Get disk usage information
-      command: df -hT
-      register: disk_usage
-
-    - name: Print disk usage in tree format
-      shell: |
-        echo "{{ disk_usage.stdout }}" | awk '
-        BEGIN {
-          print "Disk Space Usage:"
-        }
-        NR==1 {
-          printf "%-20s %-10s %-10s %-10s %-10s %-10s %s\n", $1, $2, $3, $4, $5, $6, $7
-        }
-        NR>1 {
-          printf "|-- %-16s %-8s %-10s %-10s %-10s %-10s %s\n", $1, $2, $3, $4, $5, $6, $7
-        }'
-      register: tree_output
-
-    - name: Display the tree output
-      debug:
-        msg: "{{ tree_output.stdout }}"
