- name: Enhanced Hyper-V VM List
  hosts: all
  tasks:
    - name: Get detailed VM information
      win_shell: |
        # Force array output even for single VM
        @(Get-VM) | Select-Object Name, State, 
            @{Name='CPUUsage'; Expression={$_.CPUUsage}},
            @{Name='MemoryAssignedGB'; Expression={[math]::Round($_.MemoryAssigned / 1GB, 2)}},
            Status,
            @{Name='Uptime'; Expression={$_.Uptime.ToString()}} | 
        ConvertTo-Json -Depth 4
      register: vm_info

    - name: Display formatted VM list
      debug:
        msg: |
          🖥️  {{ item.Name }}
          - State:       {{ '🟢 Running' if item.State == 2 else '🔴 Stopped' }}
          - CPU Usage:   {{ item.CPUUsage }}%
          - Memory:      {{ item.MemoryAssignedGB }} GB
          - Status:      {{ item.Status }}
          - Uptime:     {{ item.Uptime.split('.')[0] }}
      loop: "{{ (vm_info.stdout | from_json) | list }}"
      loop_control:
        label: "{{ item.Name }}"
