---
- name: Simple SFTP Test
  hosts: localhost
  gather_facts: no
  vars:
    sftp_host: "dmnetcloud"
    sftp_port: "2022"
    sftp_user: "dharmesh"
    sftp_password: "Thankgod@123"
    remote_path: "/imp/sfs_ansible"
    test_file: "/tmp/sftp_test.txt"

  tasks:

    - name: Create a test file
      copy:
        content: "Ansible SFTP test file"
        dest: "{{ test_file }}"

    - name: Upload test file via SFTP (Port 2022)
      shell: "sshpass -p '{{ sftp_password }}' sftp -o StrictHostKeyChecking=no -P {{ sftp_port }} {{ sftp_user }}@{{ sftp_host }} <<< $'put {{ test_file }} {{ remote_path }}'"

    - name: Remove local test file
      file:
        path: "{{ test_file }}"
        state: absent

    - name: Test completed
      debug:
        msg: "SFTP test completed successfully!"
