---
- name: Create and Copy Test Folder to SFTP
  hosts: all
  gather_facts: no
  vars:
    test_folder: "/tmp/test_folder"
    sftp_host: "dmnetcloud"
    sftp_port: "2022"
    sftp_user: "dharmesh"
    sftp_password: "Thankgod@123"
    remote_path: "/imp/sfs_ansible"

  tasks:
    - name: Create a test folder in /tmp
      file:
        path: "{{ test_folder }}"
        state: directory
        mode: '0755'

    - name: Create a test file inside the folder
      copy:
        content: "This is a test file."
        dest: "{{ test_folder }}/test_file.txt"

    - name: Archive the test folder (tar.gz)
      archive:
        path: "{{ test_folder }}"
        dest: "{{ test_folder }}.tar.gz"
        format: gz

    - name: Transfer archived test folder to SFTP server
      delegate_to: localhost
      shell: "sshpass -p '{{ sftp_password }}' sftp -o StrictHostKeyChecking=no -P {{ sftp_port }} {{ sftp_user }}@{{ sftp_host }} <<< $'put {{ test_folder }}.tar.gz {{ remote_path }}'"

    - name: Remove local archived file
      file:
        path: "{{ test_folder }}.tar.gz"
        state: absent

    - name: Debug message
      debug:
        msg: "Test folder successfully archived and transferred to SFTP!"
