- name: Playbook Name
  hosts: win1
  gather_facts: true
  tasks:
    - name :  Find all services that start with 'win'
      ansible.windows.win_service_info:
          name : BITS 
      register: win_service 

    - name : debug
      debug : 
        var: win_service
    - name : Find
      win_find:
        paths: C:\temp\
      register: win_find  
    - name : Debug
      debug:
        msg: "Files found: {{ win_find.files|length}}"
        msg:  |
               {% for file in win_find.files %}
               {{ file.filename }}
               {% endfor %}
    - name : File Name
      debug:
        msg: "Files found: {{ win_find.files|length}}"
    