---
- name: Test TrueNAS Scale connection and get facts
  hosts: localhost
  gather_facts: no
  collections:
    - arensb.truenas

  tasks:
    - name: Fetch all TrueNAS facts (debug structure)
      truenas_facts:
      register: truenas_info

    - name: Show all returned facts from TrueNAS
      debug:
        var: truenas_info
