---
- name: Windows Update Playbook
  hosts: all
  gather_facts: true
  tasks:
    - debug:
      var: ansible_facts["memory_mb"]|type_debug
    - debug: 
        var: ansible_facts["machine"]|type_debug


    - name: Apply update programs
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - Updates
        server_selection: managed_server
        state: "{{Update_State}}"
      register: result

    - debug: var=result
