---
- name: Windows Update Playbook
  hosts: all
  
  tasks:
    - name : Show details
    - debug:
        msg: my Machine name is  {{ansible_hostname}} 
            
        
     

    - name: Apply update programs
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - Updates
        server_selection: managed_server
        state: "{{Update_State}}"
      register: result

    - debug: var=result
