---
- name: Windows Update Playbook
  hosts: all
  gather_facts: true
  tasks:
    - debug:
       msg:
       - " Data type of 'ansible_architecture'  is {{ ansible_architecture | type_debug }} "
       - " Data type of 'ansible_all_ipv4_addresses' is {{ ansible_all_ipv4_addresses | type_debug }} "
      

    - name: Apply update programs
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - Updates
        server_selection: managed_server
        state: "{{Update_State}}"
      register: result

    - debug: var=result
