- name: Windows Update Playbook
  hosts: all
  gather_facts: no
  tasks:
    - name: Ensure Windows Update service is running
      ansible.windows.win_service:
        name: wuauserv
        state: started
        start_mode: auto

    - name: Apply Windows updates
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        reboot: true
        reboot_timeout: 1800
        log_path: C:\Windows\Temp\ansible_updates.log
        state: installed
      register: update_result

    - name: Display updates installed
      debug:
        var: update_result.updates
