- name: Windows Update Playbook
  hosts: all
  tasks:
    - name: Apply update programs
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
        server_selection: "windows_update"
        skip_optional: True
        state: installed
        reboot: true
