---
- name: Windows Update Playbook
  hosts: all
  gather_facts: true
  tasks:
    - name : Show details
    debug:
       msg: Machine name is "{{nasible_hostname}}" 
     

    - name: Apply update programs
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - Updates
        server_selection: managed_server
        state: "{{Update_State}}"
      register: result

    - debug: var=result
