 name: Install all security, critical, and rollup updates without a scheduled task

  hosts: win
  tasks:
  - name: SecurityUpdates
    win_updates:
      state: searched
      log_path: C:\ansible_wu.txt
