---
- name: Windows Update Playbook
  hosts: all
  
  tasks:
    - name : Show details
      debug:
        msg: my Machine name is  {{ansible_hostname}} 
              and OS Type is {{ansible_os_product_type}} 
               OS Build version is {{ansible_distribution_version}}
              Interface details  is {{ansible_ip_addresses | first}}
    - name: Apply update programs
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - Updates
        server_selection: managed_server
        state: "{{Update_State}}"
      register: result
    
    - debug: var=result
