---
- name: Windows Update Playbook
  hosts: all
  gather_facts: true
  tasks:
    - setup:
      register: ansible_facts
    - debug:  item
      with_dict: ansible_facts  

    - name: Apply update programs
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - Updates
        server_selection: managed_server
        state: "{{Update_State}}"
      register: result

    - debug: var=result
