---
- name: Windows Update Playbook
  hosts: all
  gather_facts: false
  tasks:
    - name: Apply update programs
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - Updates
      state: downloaded
      register: result

    - debug: var=result
