---
- name: Windows Update Playbook
  hosts: all
  gather_facts: true
  tasks:
    - Name: Start Windows Update service
      win_service: 
        name: wuauserv
        state: started
        start-mode: manual
    - name: Apply update programs
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - Updates
        server_selection: windows_update
        state: "{{Update_State}}"
      register: result

    - debug: var=result
