---

- name: Windows Service Playbook
  hosts: all
  gather_facts: false
  tasks:

   - name: service start
     win_service: 
      name: "{{servicename}}"
      state: "{{Service_state}}"  
     register: service   
    
   - name: debug
     debug: 
      var: service   

